name: sudoku-star

services:
  sudoku:
    image: jacurtwongapp/sudoku-star:latest
    container_name: sudoku-star
    ports:
      - "8180:3000"
    volumes:
      - sudoku-star-data:/app/data
    restart: always

volumes:
  sudoku-star-data:
